# Generated by Django 3.2 on 2023-06-03 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20230602_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='address',
            field=models.TextField(default='Seoul, Republic of Korea', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('recent_msg', models.BooleanField(default=False)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.real_estate')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
