# Generated by Django 3.1.6 on 2023-05-26 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lion_emoji',
            field=models.ManyToManyField(blank=True, related_name='lion_emoji_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='lion_emoji_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
