# Generated by Django 3.1.6 on 2023-05-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230526_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='lion_emoji_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
